server:
  port: 8082
  netty:
    connection-timeout: 2000

spring:
  application:
    name: redirector-service
  config:
    import: "optional:configserver:http://localhost:8888/"

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "redirector-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  kafka:
    campaign-topic: "ad-campaign-events"