server:
  port: 8083

spring:
  application:
    name: stats-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ad_broker_db
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: stats

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: stats
    default-schema: stats
    create-schemas: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "stats-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  kafka:
    click-topic: "ad-clicks"